version: '3'
services:
  # 개발환경
  <PROJECT_NAME>:
    image: <PROJECT_NAME>:<BUILD_VER>
    container_name: <PROJECT_NAME>
    networks:
      - infra_network
    # 포트 포워딩
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
    restart: always
    volumes:
      - ./log:/log


networks:
  infra_network:
    driver: bridge
    external: true
    internal: true